### ISSUE TITLE
New cloud API

### ISSUE THREAD

**Issue by vantech14** [dehsgr/node-red-contrib-alphaess#10]
Hi,

I can see there has been some movement on the official cloud API. 

Can you advise when/if this NR integration will be updated with this new API?

Thanks.

**Comment by dehsgr** [comment]
@vantech14 you can give it a first try using [Open API branch](/dehsgr/node-red-contrib-alphaess/tree/Open-API). This is still work in progress because there are currently data missing which are used via the monitoring portal's API. Feel free to try it out – I would really appreciate your feedback!

**Comment by vantech14** [comment]
@dehsgr thanks, will check it out next week as I'm currently on vacation. Looking forward to it.

**Comment by vantech14** [comment]
Hi @dehsgr i am trying to figure out how to add this new integration to Nodered?

Thanks.

**Comment by dehsgr** [comment]
e.g. with overriding files or as described here: https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm

**Comment by vantech14** [comment]
@dehsgr haven't been able to work on this yet but will try tomorrow. How far are you from a public release of the new integration?

**Comment by dehsgr** [comment]
Sorry for my late replay. Public release depends on Alpha ESS progress on their API and its release.

**Comment by vantech14** [comment]
Hi @dehsgr hope all is well. What is the latest on this? 

Thanks.

**Comment by dehsgr** [comment]
@vantech14 the same as on 2nd of April. ;-)

**Comment by dehsgr** [comment]
Published new v2 talking against open API.
