### ISSUE TITLE
Error: connect EHOSTUNREACH 20.198.228.60:443

### ISSUE THREAD

**Issue by neiloakley** [dehsgr/node-red-contrib-alphaess#11]
`There was an error during authentication at Alpha ESS monitoring portal: Error: connect EHOSTUNREACH 20.198.228.60:443`

`There was an error fetching realtime data for AL7001020100055: Error: connect EHOSTUNREACH 20.198.228.60:443`

Two issues in the log for the last 12 hours.

**Comment by dehsgr** [comment]
Because the Alpha ESS host was not reachable. Did you recognize any other issue? Aren‘t data not incoming as expected? Or is this really only that two times?

**Comment by neiloakley** [comment]
It wasn’t retrieving any data, but it seems to have resolved itself about an hour ago. Maybe downtime/maintenance on ESS side.
