### ISSUE TITLE
Authentication error since update from 4th of November 

### ISSUE THREAD

**Issue by MagerH** [dehsgr/node-red-contrib-alphaess#12]
Hello, since today's update of the Alpha Cloud, the node node-red-contrib-alphaess 1.8.4 can no longer retrieve data: 
Error message: 
```

There was an error during authentication at Alpha ESS monitoring portal: TypeError: Cannot read properties of undefined (reading 'AccessToken')

We got the following unprocessable body:
{"code":6026,"msg":"404 NOT_FOUND"}
```

Can I fix this error myself or need to change something on the node?

**Comment by dehsgr** [comment]
Hi @MagerH,

I just published v1.8.5 (see commit #[12e8920](https://github.com/dehsgr/node-red-contrib-alphaess/commit/12e892011d574da0c4fd13c0c384e2f461d00daf)). This should fix your issue(s) for now, as Alpha ESS just switched their cloud API URLs. Nevertheless we don't know, when Alpha ESS will deactivate the old system at all.

As you might see on this repository there is another branch (see [Open-API](https://github.com/dehsgr/node-red-contrib-alphaess/tree/Open-API)). This branch is able to communicate with new open API from Alpha ESS. This API isn't released yet.  But I recommend you to check it out and give feedback here: #10. 

I would like you to leave your feedback for both methods. Have a nice weekend.

**Comment by MagerH** [comment]
Hello,
thanks a lot, the node works fine now.
I already have read about the new Open-API several times and I will try to get it work for me, but I think, I will need more time. 
Have a nice Weekend too.
Henry

**Comment by neiloakley** [comment]
Node-Red still thinks 1.8.3 is the latest so I can't update through palette manager. Can you push 1.8.5 onto node-red too please?

**Comment by dehsgr** [comment]
I already did. ;-)
