### ISSUE TITLE
Missing raw entity

### ISSUE THREAD

**Issue by KortgatGH** [dehsgr/node-red-contrib-alphaess#13]
@dehsgr first of all thanks for saving us non-programmers with your fantastic skills and quick response to Alpha's changes. 
In the past I had access to an entity "payload.rawdata.realtime.ups_model" that seemed to have disappeared. This was the only way for me to detect if the grid was present or not. Am I just being half blind or is it perhaps hidden elsewhere now?

**Comment by dehsgr** [comment]
This seems to be missing in open API. Feel free to report this in that repository: https://github.com/alphaess-developer/alphacloud_open_api
