### ISSUE TITLE
How to use or get the data from this flow

### ISSUE THREAD

**Issue by tbgoose** [dehsgr/node-red-contrib-alphaess#14]
Hi all

Very new to NodeRed, so apologies if this could be posted elsewhere.

I can install the package in node-red, and add my appid and secret, and it does pull my SN from AlphaESS so it looks like it is working. But then what do I need to do to actually get / look at my inverter data?

**Comment by dehsgr** [comment]
@tbgoose I suggest to place a debug node on your flow and connect it to your alpha node. Afterwards you should see data from within node-red‘s debug window. That might give you a first impression of what to do next step(s).

More help related to node-red you will get in that community at https://discourse.nodered.org/ or from within node-red‘s documentation.

**Comment by tbgoose** [comment]
Thanks I have done this and I get the following error.

> There was an error communicating with Alpha Services: This appId is not bound to the SN (6005)

Think I need to contact AlphaESS now and see what is going on.

**Comment by dehsgr** [comment]
@tbgoose did you already register your S/N with check code at open API portal? The error you posted states that you didn‘t.

**Comment by tbgoose** [comment]
Yes I did, but I can't remove it and re-add it to see if that fixes (see https://github.com/alphaess-developer/alphacloud_open_api/issues/47). I think something is wrong on the AlphaESS side. Pity their support is so slow.

**Comment by dehsgr** [comment]
I‘m very sorry and hope that Alpha ESS will help you ASAP.
