### ISSUE TITLE
V 2.0.2

### ISSUE THREAD

**Issue by Phil-VK6PH** [dehsgr/node-red-contrib-alphaess#15]
Thank you very much for your Alphaess code.  I've been using v1.8.5 for a while but just recently this no longer works.  I think due to changes Alpha ESS have made.

So I have updated to v2.0.2 but I can't get this to work.  When I configure the node then all I see is 
Name  Alpha ESS Monitoring
App ID
Secret

I've obtained these settings from Alpha ESS and the code starts but I then get an error message
"There was an error communicating with Alpha Services: The request timestamp is not within the validity period (6009)"

I've also tried using an input so I can send a request but I then get an error message
"For being able to use input, you must switch over to manual mode."

I don't know how to switch to manual mode. 

Could you please advise how to make v2.0.2 work.

Thank you.

**Comment by dehsgr** [comment]
Strange behaviour. I would like you to triple-check your timezone and date time settings. The error reported is obvious. Until these information are matching you wouldn’t get manual mode running at all. You might take a look to your host system and/or node-red instance configuration.

**Comment by Phil-VK6PH** [comment]
Thank you for your reply.  If I use Timestamp to send the current time then I get:
2024-01-22T05:56:55.184Z

Which is UTC time so 8 hours behind my current time.  So do I need to change my time zone and if so how do I do this please?

**Comment by dehsgr** [comment]
Okay. This sounds okay. Did you register your system serial in open API portal correctly? Please triple-check it. And further take a look to https://github.com/alphaess-developer/alphacloud_open_api/issues (open and closed issues, primarily last ones). There are related errors with that message. This message isn‘t always leading to the root cause.

**Comment by Phil-VK6PH** [comment]
In /issues  closed I found this timestamp error.  The user found that whitelist had been enabled on his account and he didn't know how.  I'm not sure where to find this?

**Comment by dehsgr** [comment]
You‘ve to check that in open API portal at https://open.alphaess.com.

**Comment by Phil-VK6PH** [comment]
My whitelist is not enabled.

**Comment by Phil-VK6PH** [comment]
I think there is an error in my open.alphaess.com account.  I'll contact Alpha ESS and get them to fix this for me.  
Thanks for your assistance.

**Comment by dehsgr** [comment]
Ok. Thank you for that information.
