### ISSUE TITLE
Issue with Redmatic Version 7.3.4

### ISSUE THREAD

**Issue by Matze2023** [dehsgr/node-red-contrib-alphaess#16]
Hi, I found this Node and was super happy. I tried to install and node and get an error message (engine Not compatible with your version of node/npm: @azure/msal-node@1.18.4). I am using an Raspberrymatic with Redmatic Version 7.3.4. Many thanks for your reply. - Mat

**Comment by dehsgr** [comment]
@Matze2023 you would have to update very old node-red version from you redmatic instance or use another and newer node-red instance e.g. in a docker container.

**Comment by Matze2023** [comment]
Many thanks, for your reply 🙏 I do have Node-Red Version 3.1.3 installed. Is this a very old/too old version?

**Comment by dehsgr** [comment]
Sorry, my fault, @Matze2023. I would like you to check your underlying nodejs AND npm version. This seems to be a bit too old for indirect dependency azure/msal-node@1.18.4. See https://www.npmjs.com/package/@azure/msal-node?activeTab=readme#prerequisites for prerequisites.

**Comment by Matze2023** [comment]
Many thanks! I checked my system and uninstalled Redmatic 7.3.1, going back to Version 7.2.1

In this version, it works. Thanks.

Background:

I updated my system several months ago via this flow: https://homematic-forum.de/forum/viewtopic.php?t=81303

It worked pretty well, but since then, I haven't been able to update and install nodes.

**Comment by dehsgr** [comment]
Thanks for your feedback and have a nice rest of sunday – especially today at 21 o‘clock :)

**Comment by Matze2023** [comment]
Thank you very much. In the end at least the draw came out. have a good start to the week
