### ISSUE TITLE
Request failed with status code 502

### ISSUE THREAD

**Issue by neiloakley** [dehsgr/node-red-contrib-alphaess#17]
Unable to connect. Error is:

“18/09/2024, 16:23:22[node: Alpha ESS](http://192.168.7.7:1880/#)
msg : string[105]
"There was an error communicating with Alpha Services: AxiosError: Request failed with status code 502 (0)"
18/09/2024, 16:23:39[node: Alpha ESS](http://192.168.7.7:1880/#)
msg : string[105]
"There was an error communicating with Alpha Services: AxiosError: Request failed with status code 502 (0)"
18/09/2024, 16:23:57[node: Alpha ESS](http://192.168.7.7:1880/#)
msg : string[105]
"There was an error communicating with Alpha Services: AxiosError: Request failed with status code 502 (0)"”

**Comment by dehsgr** [comment]
There is currently an issue with Alpha Servers. No issue of this node. Sorry for any inconvenience.

**Comment by dehsgr** [comment]
See https://github.com/alphaess-developer/alphacloud_open_api/issues/85.
