### ISSUE TITLE
Failure after last AlphaCloud System Update

### ISSUE THREAD

**Issue by HeinMueck01** [dehsgr/node-red-contrib-alphaess#19]
Still receiving following failure: "There was an error communicating with Alpha Services: Error: Client network socket disconnected before secure TLS connection was established (0)" and "There was an error communicating with Alpha Services: AxiosError: Request failed with status code 500 (0)". The node-red-contrib-alphaess 2.0.2 was running more than 8 month without problems until the AlphaCloud System Update last week. What can be done?

**Comment by dehsgr** [comment]
Not an issue of this node. We‘ve to wait for Alpha ESS and their completion of maintenance with some patience ([see here](https://github.com/alphaess-developer/alphacloud_open_api/issues/89#issuecomment-2414598901)). Cross-posting doesn‘t bring us forward.
