### ISSUE TITLE
There was an error during login operation into Alpha ESS monitoring portal

### ISSUE THREAD

**Issue by str3000** [dehsgr/node-red-contrib-alphaess#5]
I see, there exists an update. I installed it and it works. Fantastic.
Thanks a lot!

Since today I do not get any values.
I use node-red in ioBroker.
Works fine without any error over weeks. Thanks to the programmer(s).

Message:
There was an error during login operation into Alpha ESS monitoring portal: SyntaxError: Unexpected token  in JSON at position 0

We got the following unprocessable body:
![grafik](https://user-images.githubusercontent.com/48569357/194768686-564e1860-5115-4083-b541-ab219830cb54.png)

**Comment by str3000** [comment]
I see, there exists an update. I installed it and it works. Fantastic.
Thanks a lot!

**Comment by dehsgr** [comment]
You're welcome. Alpha ESS changed some kind of compression settings in their backend today causing this issue.

**Comment by dehsgr** [comment]
This is related to #4.
