### ISSUE TITLE
login in error 

### ISSUE THREAD

**Issue by str3000** [dehsgr/node-red-contrib-alphaess#6]
problem since today
verson: 1.6.0

error:
16.10.2022, 13:38:36[node: Alpha EES Monitoring](http://192.168.1.137:1880/?instance=0&newReact=true&0&react=blue#)
msg : string[163]
"There was an error during login operation into Alpha ESS monitoring portal: SyntaxError: Unexpected end of JSON input↵↵We got the following unprocessable body:↵"

**Comment by dehsgr** [comment]
Alpha ESS changed the underlying web portal API. Currently I don't see an option to get this working again. Any help on reverse engineering how new authentication scheme (authsignature/authtimestamp) works is really appreciated...

**Comment by dehsgr** [comment]
> Signature verification and anti-crawl data functionality are added in all APIs of AlphaCloud.

That's our issue now (since Alpha Cloud v5.0.0.2).

**Comment by dehsgr** [comment]
I just published an update working around this issue with additional data retrievable via browsers debugging console (see commit [2efa623](https://github.com/dehsgr/node-red-contrib-alphaess/commit/2efa623a44420ea486ca6b2368b8b8402f9aab72). Updated [README.md](https://github.com/dehsgr/node-red-contrib-alphaess/blob/main/README.md) accordingly.

Not sure how long this works and when additional auth data will become invalid. This is only a hack for getting around this for the moment until there will be more information available to solve this issue.

**Comment by str3000** [comment]
iI make the update to 1.6.1 and same behavior..

16 Oct 18:12:48 - [warn] [alphaess-monitoring:Alpha EES Monitoring] There was an error during login operation into Alpha ESS monitoring portal: SyntaxError: Unexpected end of JSON input
 
 We got the following unprocessable body:

**Comment by dehsgr** [comment]
@str3000 so I assume you didn't read the [README.md](https://github.com/dehsgr/node-red-contrib-alphaess/blob/main/README.md) as mentioned [here](https://github.com/dehsgr/node-red-contrib-alphaess/issues/6#issuecomment-1279966123). You've to fetch authsignature and authtimestamp yourself from your browser's debug console and give that data to the node too... ;-)

**Comment by str3000** [comment]
your right i, sorry

**Comment by str3000** [comment]
Node running again.
Thanks for the super fast fix.

You write it and I think also this method will only work for a short time. Hopefully ....
Have a nice evening!

**Comment by dehsgr** [comment]
Thank you! You're welcome. Have a nice evening too!

**Comment by dehsgr** [comment]
Published a fix with v.1.7.0. Thanks for reporting and supporting.
