### ISSUE TITLE
Unable login to api interface

### ISSUE THREAD

**Issue by Z0472** [dehsgr/node-red-contrib-alphaess#7]
Node red debug info: 

There was an error during login operation into Alpha ESS monitoring portal: TypeError: Cannot read properties of undefined (reading 'AccessToken')

We got the following unprocessable body:
{"code":9006,"info":"Network exception, please try again later!","exMessageInfo":"Please use web browser to view the data"}

**Comment by dehsgr** [comment]
Please update to newest version and confirm fix.

**Comment by Z0472** [comment]
It works After upgrade to 1.8.0
