### ISSUE TITLE
It stoped work after cloud upgrade

### ISSUE THREAD

**Issue by Z0472** [dehsgr/node-red-contrib-alphaess#9]
Hi all, 
today around 15:00 the sensors stopped showing values:
in the debug window of node red (HomeAssistant)  is written : 

There was an error during fetching Alpha ESS Signature Key: We got an unexpected body.

We got the following body:
(window.webpackJsonp=window.webpackJsonp||[]).push([["app"],{"/fHe":function(e,t,r){},"0Fbn":function(e,t,r){"use strict";r.r(t);var a=r("4BeY"),A=r.n(a),i=r("IaFt"),n=r.n(i),o=new A.a({id:"icon-people",use:"icon-people-usage",viewBox:"0 0 128 128",content:'<symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" id="icon-people"><path d="M104.185 95.254c8.161 7.574 13.145 17.441 13.145 28.28 0 1.508-.098 2.998-.285 4.466h-10.784c.238-1.465.403-2.948.403-4.465 0-8.983-4.36-17.115-11.419-23.216C86 104.66 75.355 107.162 64 107.162c-11.344 0-21.98-2.495-31.22-6.83-7.064 6.099-11.444 14.218-11.444 23.203 0 1.517.165 3 .403 4.465H10.955a35.444 35.444 0 0 1-.285-4.465c0-10.838 4.974-20.713 13.127-28.291C9.294 85.42.003 70.417.003 53.58.003 23.99 28.656.001 64 .001s63.997 23.988 63.997 53.58c0 16.842-9.299 31.85-23.812 41.673zM64 36.867c-29.454 0-53.33-10.077-53.33 15....

and in log of Node-red add ons is a very big list  in diferent languages : 

consegna",client:"cliente",pleaseEnterContent:"Inserisci il contenuto",cancel:"Annulla",save:"salvare",pleaseFillInTheRemarks:"Per favore, compila i commenti",pleaseCheckTheSerialNumberFirst:"Verificare prima il numero di serie",successfulOperation:"Operazione di successo",successfullyDeleted:"cancellato correttamente"}}},wWzq:function(e,t,r){},"wo5+":function(e,t,r){"use strict";r.r(t);var a=r("4BeY"),A=r.n(a),i=r("IaFt"),n=r.n(i),o=new A.a({id:"icon-sliders",use:"icon-sliders-usage",viewBox:"0 0 24 24",content:'<symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" id="icon-sliders"><line x1="4" y1="21" x2="4" y2="14" /><line x1="4" y1="10" x2="4" y2="3" /><line x1="12" y1="21" x2="12" y2="12" /><line x1="12" y1="8" x2="12" y2="3" /><line x1="20" y1="21" x2="20" y2="16" /><line x1="20" y1="12" x2="20" y2="3" /><line x1="1" y1="14" x2="7" y2="14" /><line x1="9" y1="8" x2="15" y2="8" /><line x1="17" y1="16" x2="23" y2="16" /></symbol>'});n.a.add(o);t.default=o},wy2R:function(e,t){e.exports=moment},xd0U:function(e){e.exports={navbar:{logOut:"退出登录",userInfoSettting:"用户信息设置"},route:{productManualLink:"产品说明列表",customerArchivesAdd:"客户档案新增",customerArchivesDetail:"客户档案详情",productRecommemdationsEdit:"产品建议编辑",attachmentDetails:"客诉详情信息",customerComplaintEdit:"客诉编辑",cusHandleRecord:"客户档案记录",setAdministrator:"设定用户组管理员",associatedCountry:"关联国家区域",associatedSNCodingRules:"关联SN编码规则",associatedInverter:"关联逆变器型号",oneClickUpgradeManagementDetail:"装机升级详情",oneClickUpgradeManagementAdd:"装机升级新增",WarrantyModule:"上传送货单",InstallationInteraction:"安装交互",Warranty:"质保",QualityAssuranceManagement:"质保管理",warrantyCodeMaintenance:"延保代码维护",warrantyList:"质保列表",BusinessAndIndustryData:"工商业数据导出",DataManagementExport:"常规数据导出",NMIManagement:"NMI管理",RAndDtimereport:"研发工时报表",addProductSuggestion:"新增产品建议",appUpdatesManage:"固件版本更新管理",basicSettings:"基础设置",cdgl:"菜单管理",gridConnectedRuleConfigManage:"并网法规配置管理",chargingPileConfiguration:"充电桩配置",clientList:"客户列表",cm:"指令管理",comDataManage:"通讯数据管理",productModelConfigurationManagement:"产品配置管理",batteryModelConfiguration:"电池型号配置",electricMeterModelConfiguration:"电表型号配置",createComplaint:"创建客诉",customerComplaint:"客诉",customerComplaintList:"客诉列表",elePricesSetting:"电价设置",energyStorageSystemAss:"关联新设备",fa:"错误报表",firmwareManagement:"固件版本管理",fygl:"翻译管理",gzdmjxwh:"故障代码解析维护",home:"首页",ians:"安装新设备",imprint:"联系信息",installChargingPile:"安装充电桩",ir:"安装记录查询",jsgl:"角色管理",khfk:"客户反馈",ligl:"License管理",zxzh:"注销账号",listOfStorageSys:"储能系统列表",menuManage:"菜单管理",myxx:"我的消息",otherInfo:"其他信息",privacypolicy:"隐私政策",productRecommendations:"产品建议",ProductSatisfactionSurvey:"产品满意度调研",productRecommendationsList:"产品建议列表",reportDataExport:"报表数据导出",routedNetwork:"馈网控制",runDataModify:"运行数据修正",sbs:"系统批量设置",sdm:"系统数据迁移",sfc:"系统故障查询",sjbbsczk:"数据报表生成状况",smr:"系统维修记录查询",sngl:"SN管理",statisticalStatement:"统计报表",storageSysMaintenance:"储能系统维护",vppgl:"VPP管理",xgmm:"修改密码",xtszz:"系统设置",xtxxhz:"系统信息汇总",informationCenter:"资料中心",productManual:"产品资料",dataColumnManagement:"资料栏目管理",xxfsgl:"消息发布管理",ycdssj:"远程定时升级管理",yhgli:"用户管理",yhrz:"用户日志",yhxxsz:"用户信息设置",appbbwh:"APP版本维护",inverterTypeNumberConfiguration:"逆变器型号配置",dataCentreManagement:"资料中心管理",installStepManagement:"安装步骤管理",oneClickUpgradeManagement:"一键升级管理",newSnstallationUpgradeStrategy:"新装机升级策略",oneClickUpgradeFeedbackList:"一键升级反馈列表",afterSaleBatchUpgrade:"售后批量升级",upsModeConfig:"UPS配置管理",messageList:"留言列表",userGroupManagement:"用户组管理",accountManage:"账号管理",orderManageToBeIssued:"出库订单管理",orderToBeWarehousedManage:"入库订单管理",toBeOutboundPickingListManage:"出库订单管理",manageOfIncomingMaterialReturnOrders:"入库订单管理",stockManagement:"库存管理",salesOrderReportPage:"销售订单列表",pickingOrderReportPage:"交货单报表",inventoryQuery:"库存查询",postingManagement:"过账管理",customerManagement:"客户管理",Upgrade:"升级管理",aboutAlphaCloud:"关于AlphaCloud",updateLog:"更新日志",gxrzgl:"更新日志管理",gxtzgl:"更新通知管理",reportManagement:"报表管理",licenseReport:"License报表",warrantyCodeRecord:"质保Code使用记录",menuPermissions:"权限菜单",menuTranslation:"菜单翻译管理",userMenuManagement:"用户菜单权限管理",rolesManagement:"角色管理"}}},"y/lp":function(e,t,r){"use strict";r.r(t);var a=r("4BeY"),A=r.n(a),i=r("IaFt"),n=r.n(i),o=new A.a({id:"icon-feedback",use:"icon-feedback-usage",viewBox:"0 0 1024 1024",content:'<symbol class="icon" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="icon-feedback"><defs><style type="text/css"></style></defs><path d="M892.032 160H131.968C94.528 160 64 190.464 64 228.032v512c0 37.504 30.464 67.968 68.032 67.968H237.44l0.64 139.52a8 8 0 0 0 12.352 6.656l224.64-146.176h416.832c37.568 0 68.032-30.464 68.032-68.032v-512c0-37.504-30.464-67.968-68.032-67.968z m-4.032 576H453.824l-144.192 93.824-0.384-85.824a8 8 0 0 0-8-8H136V232h752V736zM267.008 355.968h489.984c5.312 0 8 2.688 8 8v48c0 5.376-2.688 8-8 8H267.008c-5.312 0-8-2.624-8-8v-48c0-5.312 2.688-8 8-8z m0 166.016h489.984c5.312 0 8 2.688 8 8v48c0 5.376-2.688 8-8 8H267.008c-5.312 0-8-2.624-8-8v-48c0-5.312 2.688-8 8-8z" p-id="8984" /></symbol>'});n.a.add(o);t.default=o},y4PM:function(e,t,r){},y8zc:function(e){e.exports={navbar:{logOut:"Logout",userInfoSettting:"Benutzereinstellung"},route:{productManualLink:"Produktbeschreibungsliste",customerArchivesAdd:"Kundenprofil hinzugefügt",customerArchivesDetail:"Kundenprofildetails",productRecommemdationsEdit:"ProduktvorschlägeBearbeiten",attachmentDetails:"Details der Kundenbeschwerde",customerComplaintEdit:"KundenbeschwerdeBearbeiten",cusHandleRecord:"Kundendateiaufzeichnungen",setAdministrator:"Benutzergruppenadministrator festlegen",associatedCountry:"Zugehöriger Länderbereich",associatedSNCodingRules:"Zugehörige SN-Codierungsregeln",associatedInverter:"Zugehöriges Invertermodell",oneClickUpgradeManagementDetail:"Installations- und Upgrade-Details",oneClickUpgradeManagementAdd:"Installations-Upgrade hinzugefügt",WarrantyModule:"Lieferschein hochladen",InstallationInteraction:"interaktiv installieren",Warranty:"Gewährleistung",QualityAssuranceManagement:"Qualitätssicherungsmanagement",warrantyCodeMaintenance:"Verwaltung Garantiecodes",warrantyList:"Garantieliste",BusinessAndIndustryData:"Industrie und Gewerbe",DataManagementExport:"Routinedaten exportieren",NMIManagement:"NMI

**Comment by vantech14** [comment]
Same as me

![image](https://user-images.githubusercontent.com/76781626/202862719-1884b7c1-f47c-43c3-83f7-bfb439fde806.jpeg)

App states the cloud will be updated today.

**Comment by dehsgr** [comment]
Just published v1.8.3. ;-)

**Comment by Z0472** [comment]
It works again. Thank you very much. 
BR Zdenek
